/*Written by Monika Golla
 *This Java file is to generate assert statements for each predicate of the given program. That is for each predicate in the Condition_And_Predicates.txt file the corresponding metaFileOfPred-*.txt is generated by considering test cases in predicateResults*.txt respectively.
 */


import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;

public class MetaJavaFileGenerator {
    public static void main(String[] args) throws FileNotFoundException, IOException {

        BufferedReader PC=new BufferedReader(new FileReader("exp/Condition_And_Predicates.txt"));
        String r=PC.readLine();
        int no_of_pred=0;

        while(r!=null){

	    String predicate = r;
            if(r.contains("&&")||r.contains("||")){

            	r=r.replace("&&", "~");
            	r=r.replace("||", "~");
	    	r=r.replace("(", "");
	    	r=r.replace(")", "");
            	String p[]=r.split("~");
            	no_of_pred++;
	    	BufferedReader PC1=new BufferedReader(new FileReader("exp/predicateResults"+no_of_pred+".txt"));
	    	PrintWriter out_cp_onlyvalue=new PrintWriter("exp/meta/metaFileOfPred-"+no_of_pred+".txt");
            
            	String r1=PC1.readLine();
	    	String tVal[] = null;
	    	for(int n1=0;n1<p.length;n1++){
			
			while(r1!=null){

	        		tVal=r1.split(",");
				String finalPredicate = predicate;
				for(int n2=0;n2<tVal.length;n2++){

					System.out.println(tVal[n2]);
					if(tVal[n2].equals("F")){

						System.out.println("!"+p[n2] + finalPredicate.contains(p[n2]));
                                		finalPredicate = finalPredicate.replace(p[n2],"!("+p[n2]+")");

					}else
						System.out.println(p[n2]);

				}
		
					
				System.out.println("*********************"+finalPredicate);
				out_cp_onlyvalue.println("__CPROVER_assert(! "+finalPredicate+" );");
				out_cp_onlyvalue.flush();	
				tVal=null;
				r1=PC1.readLine();
	
			}

	    	}
	    
	    	System.out.println("*********************"+p.length);

            }
            r=PC.readLine();

        }
            
    }
}
