/*Written by Monika Golla
 *This Java file is to generate assert statements for each predicate of the given program. That is for each predicate in the Condition_And_Predicates.txt file the corresponding metaFileOfPred-*.txt is generated by considering test cases in predicateResults*.txt respectively.
*Upon generating assert statements, replaced predicate(in Condition_And_Predicates.txt file) with the corresponding assert statements(in metaFileOfPred-*.txt) while iterating each line in the given c program(test14.c). Thus generated a meta c program(test14Meta.c) which contains assert statements before each predicate (if statements).
 */



import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.*; 

/**
 *
 * @author user
 */
public class MetaJavaFileGenerator_V4{
    public static void main(String[] args) throws FileNotFoundException, IOException {

        BufferedReader PC=new BufferedReader(new FileReader("exp/Condition_And_Predicates.txt"));
        String r=PC.readLine();
        int no_of_pred=0;
	Map<String,String> mapPredicate=new HashMap<String,String>();
        
        while(r!=null){

int indexOfAnd = 0, indexOfOr = 0, count = 0;
Map<Integer,String> mapPosition=new HashMap<Integer,String>();
        while (true) {
            indexOfAnd = r.indexOf("&&", indexOfAnd);
            if (indexOfAnd != -1) {
                mapPosition.put(indexOfAnd, "&&");
                indexOfAnd += 2;
            } else {
                break;
            }
        }	
	while (true) {
            indexOfOr = r.indexOf("||", indexOfOr);
            if (indexOfOr != -1) {
                mapPosition.put(indexOfOr, "||");
                indexOfOr += 2;
            } else {
                break;
            }
        }
Map<Integer, String> sortedMapPosition = new TreeMap<Integer, String>(mapPosition);
List<Integer> sortedKeys = new ArrayList<Integer>(sortedMapPosition.keySet());	    
//Set<Integer> sortedKeys = sortedMapPosition.keySet();
	    String predicate = r;
	    String finalPredicateArray="";
            if(r.contains("&&")||r.contains("||")){

            	r=r.replace("&&", "~");
            	r=r.replace("||", "~");
	    	r=r.replace("(", "");
	    	r=r.replace(")", "");
            	String p[]=r.split("~");
            	no_of_pred++;
	    	BufferedReader PC1=new BufferedReader(new FileReader("exp/predicateResults"+no_of_pred+".txt"));
	    	PrintWriter out_cp_onlyvalue=new PrintWriter("exp/meta/metaFileOfPred-"+no_of_pred+".txt");
            
            	String r1=PC1.readLine();
	    	String tVal[] = null;
		
	    	for(int n1=0;n1<p.length;n1++){
			
			while(r1!=null){
				String finalPredicate = "";
	        		tVal=r1.split(",");
				Integer sortedKeysIndex = -1;
				for(int n2=0;n2<tVal.length;n2++){

					System.out.println(tVal[n2]);
					//Integer mapIndex=sortedKeys.get(sortedKeysIndex);
					if(tVal[n2].equals("F")){
						if(sortedKeysIndex != -1){
							System.out.println("!"+p[n2] + finalPredicate.contains(p[n2]));
                                			finalPredicate = finalPredicate + sortedMapPosition.get(sortedKeys.get(sortedKeysIndex))+ "!("+p[n2]+")";
						}else{
							System.out.println("!"+p[n2] + finalPredicate.contains(p[n2]));
                                			finalPredicate = "!("+p[n2]+")";
						}

					}else{
						if(sortedKeysIndex != -1){
							System.out.println(p[n2]);
			                        	finalPredicate = finalPredicate + sortedMapPosition.get(sortedKeys.get(sortedKeysIndex)) + p[n2];
						}else{
							System.out.println(p[n2]);
			                        	finalPredicate = p[n2];
						}
					}
					sortedKeysIndex++;

				}

				finalPredicate = "__CPROVER_assert(! ("+finalPredicate+") ,\"ASSERTION VIOLATION\");";
				finalPredicateArray = finalPredicateArray + "\n" +finalPredicate;	
				System.out.println("*********************"+finalPredicate);
				out_cp_onlyvalue.println(finalPredicate);
				out_cp_onlyvalue.flush();	
				tVal=null;

				r1=PC1.readLine();
	
			}
			
			

	    	}
	         
	    	System.out.println("*********************"+p.length);

            }
	    mapPredicate.put(predicate, finalPredicateArray);
            r=PC.readLine();

        }
	String fileName = "";
	if (args.length > 0) {
    		fileName = args[0];
    	}else{
	        System.err.println("File name not provided!");
	        System.exit(1);
    	}

	BufferedReader originalFile=new BufferedReader(new FileReader(fileName));
	String eachLine=originalFile.readLine();
	
	
        PrintWriter out_metaFile_V3=new PrintWriter("exp/meta/MetaWithBracesWhile-V3.c");
	System.out.println("*********************"+mapPredicate.size());

	while(eachLine!=null){
		for(String eachPredicate : mapPredicate.keySet()){
			if(eachLine.contains(" while(")||eachLine.contains(" while (")||eachLine.contains(" while(") ||eachLine.contains(" for(")||eachLine.contains(" for (")||eachLine.contains("  for (")){
				int k1_f=eachPredicate.indexOf('(');
				int k2_f=eachPredicate.lastIndexOf(')');
				String eachPredicate1=eachPredicate.substring(1, eachPredicate.length()-1);
				System.out.println("*********************eachPredicate "+eachPredicate1);
					if(eachLine.replaceAll("\\s+","").contains(eachPredicate1)){
						String assertStmts = mapPredicate.get(eachPredicate);
						
						eachLine=eachLine.replace(eachLine, eachLine +"\n" + assertStmts);
						if(!(eachLine.contains("||")) && !(eachLine.contains("&&"))){
							String assertStmts1 = "__CPROVER_assert("+eachPredicate1+" ,\"ASSERTION VIOLATION\");";
							String assertStmts2 = "__CPROVER_assert(! ("+eachPredicate1+") ,\"ASSERTION VIOLATION\");";
							eachLine=eachLine.replace(eachLine,eachLine + "\n" + assertStmts1 +"\n" +assertStmts2);
						}
						while(true){
							out_metaFile_V3.println(eachLine);
							out_metaFile_V3.flush();
							eachLine = originalFile.readLine();
							if(eachLine.contains("}")){
								break;
							}
						}
						eachLine=eachLine.replace(eachLine,assertStmts +"\n" + eachLine);
						if(!(eachLine.contains("||")) && !(eachLine.contains("&&"))){
							String assertStmts1 = "__CPROVER_assert("+eachPredicate1+" ,\"ASSERTION VIOLATION\");";
							String assertStmts2 = "__CPROVER_assert(! ("+eachPredicate1+") ,\"ASSERTION VIOLATION\");";
							eachLine=eachLine.replace( eachLine,"\n" + assertStmts1 +"\n" +assertStmts2 + eachLine);
						}
						break;
					}
					
			}else if(eachLine.contains("if(")){
				String eachPredicate1=eachPredicate.substring(1, eachPredicate.length()-1);
				if(eachLine.replaceAll("\\s+","").contains(eachPredicate1)){
					if(!(eachLine.contains("||")) && !(eachLine.contains("&&"))){
						String assertStmts1 = "__CPROVER_assert("+eachPredicate1+" ,\"ASSERTION VIOLATION\");";
						String assertStmts2 = "__CPROVER_assert(! ("+eachPredicate1+") ,\"ASSERTION VIOLATION\");";
						eachLine=eachLine.replace(eachLine,"\n" + assertStmts1 +"\n" +assertStmts2 + "\n" + eachLine);
					}
				}
				
			}
			
		}
		out_metaFile_V3.println(eachLine);
		out_metaFile_V3.flush();
		System.out.println("*********************"+eachLine);
		
		eachLine = originalFile.readLine();
	}

	originalFile=new BufferedReader(new FileReader("exp/meta/MetaWithBracesWhile-V3.c"));
	eachLine=originalFile.readLine();
	
        out_metaFile_V3=new PrintWriter("exp/meta/MetaWithBraces-V4.c");
	System.out.println("*********************"+mapPredicate.size());

	while(eachLine!=null){
		String removeOR=eachLine;
		for(String eachPredicate : mapPredicate.keySet()){
			if(!(eachLine.contains(" while(")||eachLine.contains(" while (")||eachLine.contains(" while(") ||eachLine.contains(" for(")||eachLine.contains(" for (")||eachLine.contains("  for (") || eachLine.contains("__CPROVER_assert("))){

			if(eachLine.replaceAll("\\s+","").contains(eachPredicate)){

				String assertStmts = mapPredicate.get(eachPredicate);
				
				if(assertStmts.contains("||")){
					assertStmts=assertStmts.replace("||", "&&");
				}
				eachLine=eachLine.replace(eachLine,assertStmts +"\n" + eachLine);
				System.out.println("*********************eachLine1 "+eachLine);
				break;
			}
			}else  if(eachLine.contains("__CPROVER_assert(")){
				eachLine=eachLine.replace("||", "&&");
			}
			
			
		}
		out_metaFile_V3.println(eachLine);
		out_metaFile_V3.flush();
		//out_metaFile_V2.println(removeOR);
		//out_metaFile_V2.flush();
		System.out.println("*********************"+eachLine);
		
		eachLine = originalFile.readLine();
	}
	
            
    }
}
