/*Written by Monika Golla
 *This Java file is to generate assert statements for each predicate of the given program. That is for each predicate in the Condition_And_Predicates.txt file the corresponding metaFileOfPred-*.txt is generated by considering test cases in predicateResults*.txt respectively.
*Upon generating assert statements, replaced predicate(in Condition_And_Predicates.txt file) with the corresponding assert statements(in metaFileOfPred-*.txt) while iterating each line in the given c program(test14.c). Thus generated a meta c program(test14Meta.c) which contains assert statements before each predicate (if statements).
 */



import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.*; 
import java.io.LineNumberReader;

/**
 *
 * @author user
 */
public class MetaJavaFileGenerator_V1{
    public static int LoopNum = 1;
    public static void main(String[] args) throws FileNotFoundException, IOException {

        BufferedReader PC=new BufferedReader(new FileReader("exp/Condition_And_Predicates.txt"));
        String r=PC.readLine();
        int no_of_pred=0;
	Map<String,String> mapPredicate=new HashMap<String,String>();
        
        while(r!=null){

	    String predicate = r;
	    String finalPredicateArray="";
            if(r.contains("&&")||r.contains("||")){

            	r=r.replace("&&", "~");
            	r=r.replace("||", "~");
		if(!r.contains("%") && !r.contains("!") && !r.contains("=")){
	    		r=r.replace("(", "");
	    		r=r.replace(")", "");
		}
            	String p[]=r.split("~");
            	no_of_pred++;
	    	BufferedReader PC1=new BufferedReader(new FileReader("exp/predicateResults"+no_of_pred+".txt"));
	    	PrintWriter out_cp_onlyvalue=new PrintWriter("exp/meta/metaFileOfPred-"+no_of_pred+".txt");
            
            	String r1=PC1.readLine();
	    	String tVal[] = null;
		
	    	for(int n1=0;n1<p.length;n1++){
			
			while(r1!=null){
				String finalPredicate = predicate;
	        		tVal=r1.split(",");
				Map<Integer, Boolean> visitedMap = new HashMap<Integer, Boolean>();
				for(int n2=0;n2<tVal.length;n2++){

					//System.out.println(tVal[n2]);
					int mainIndex = finalPredicate.indexOf(p[n2]);
					if(mainIndex == -1){System.out.println("*********************Minus one.........");
								System.out.println("*********************"+p[n2]);
								System.out.println("*********************"+finalPredicate);}
					//if(mainIndex != -1){
					if(tVal[n2].equals("F")){

						//System.out.println("!"+p[n2] + finalPredicate.contains(p[n2]));
						
						while(true){
							if(!visitedMap.containsKey(mainIndex)){
								int endIndex = mainIndex+p[n2].length();
								StringBuffer buf = new StringBuffer(finalPredicate);
                                				buf = buf.replace(mainIndex,endIndex, "!("+p[n2]+")");
								System.out.println("*********************Replacing.........");
								finalPredicate = buf.toString();
								mainIndex =mainIndex+2;
								break;
							}
							mainIndex = finalPredicate.indexOf(p[n2], mainIndex+1);
						}
						
					}else
						//System.out.println(p[n2]);
					visitedMap.put(mainIndex ,Boolean.TRUE);

				}//}

				finalPredicate = "__CPROVER_assert(! "+finalPredicate+" ,\"ASSERTION VIOLATION\");";
				finalPredicateArray = finalPredicateArray + "\n" +finalPredicate;	
				//System.out.println("*********************"+finalPredicate);
				out_cp_onlyvalue.println(finalPredicate);
				out_cp_onlyvalue.flush();	
				tVal=null;

				r1=PC1.readLine();
	
			}
			
			

	    	}
	         
	    	//System.out.println("*********************"+p.length);

            }
	    mapPredicate.put(predicate, finalPredicateArray);
            r=PC.readLine();

        }
	String fileName = "";
	if (args.length > 0) {
    		fileName = args[0];
    	}else{
	        System.err.println("File name not provided!");
	        System.exit(1);
    	}
	LineNumberReader originalFile=new LineNumberReader(new FileReader(fileName));
	String eachLine=originalFile.readLine();
	
        PrintWriter out_metaFile_V1=new PrintWriter("exp/meta/MetaWithBracesWhile-V1.c");
	//System.out.println("*********************"+mapPredicate.size());

	while(eachLine!=null){
		eachLine = genAssertForLoops(eachLine, mapPredicate,originalFile, out_metaFile_V1);
///////////////////////////////////////////////////////////////////////////////////////////
		out_metaFile_V1.println(eachLine);
		out_metaFile_V1.flush();
		//System.out.println("*********************"+eachLine);
		eachLine = originalFile.readLine();
	}
	originalFile.close();
	BufferedReader originalFile1=new BufferedReader(new FileReader("exp/meta/MetaWithBracesWhile-V1.c"));
	eachLine=originalFile1.readLine();
	
        out_metaFile_V1=new PrintWriter("exp/meta/MetaWithBraces-V1.c");
	//PrintWriter out_metaFile_V2=new PrintWriter("exp/meta/MetaWithBraces-V2.c");
	//System.out.println("*********************"+mapPredicate.size());

	while(eachLine!=null){
		for(String eachPredicate : mapPredicate.keySet()){
			if(!(eachLine.contains(" while(")||eachLine.contains(" while (")||eachLine.contains(" while(") ||eachLine.contains(" for(")||eachLine.contains(" for (")||eachLine.contains("  for (") || eachLine.contains("if(0)") || eachLine.contains("if(1)") || eachLine.contains("__CPROVER_assert("))){
			if(eachLine.replaceAll("\\s+","").contains(eachPredicate)){

				String assertStmts = mapPredicate.get(eachPredicate);
				eachLine=eachLine.replace(eachLine,assertStmts +"\n" + eachLine);//to generate assert statements before if cond that are inside while and for loop
				
				break;
			}
			
			}else if(eachLine.contains(" while(0)")||eachLine.contains(" for(;0;)")||eachLine.contains("if(0)")){
				String eachPredicate1 = "1 == 0";
				String assertStmts1 = "__CPROVER_assert("+eachPredicate1+" ,\"ASSERTION VIOLATION\");";
				String assertStmts2 = "__CPROVER_assert(! ("+eachPredicate1+") ,\"ASSERTION VIOLATION\");";
				eachLine=eachLine.replace(eachLine,"\n" + assertStmts1 +"\n" +assertStmts2 + "\n" + eachLine);
			}else if(eachLine.contains(" while(1)")||eachLine.contains(" for(;1;)")||eachLine.contains("if(1)")){
				String eachPredicate1 = "1 == 1";
				String assertStmts1 = "__CPROVER_assert("+eachPredicate1+" ,\"ASSERTION VIOLATION\");";
				String assertStmts2 = "__CPROVER_assert(! ("+eachPredicate1+") ,\"ASSERTION VIOLATION\");";
				eachLine=eachLine.replace(eachLine,"\n" + assertStmts1 +"\n" +assertStmts2 + "\n" + eachLine);
			}
			
		}
		out_metaFile_V1.println(eachLine);
		out_metaFile_V1.flush();
		//out_metaFile_V2.println(removeOR);
		//out_metaFile_V2.flush();
		//System.out.println("*********************"+eachLine);
		
		eachLine = originalFile1.readLine();
	}
	
	LineNumberReader lineNumberReader = new LineNumberReader(new FileReader("exp/meta/MetaWithBraces-V1.c"));
	eachLine=lineNumberReader.readLine();
	PrintWriter out_metaFile_Loop=new PrintWriter("exp/meta/LoopAssertStatements.csv");
	
	while(eachLine!=null){
			//System.out.println("Reading"+eachLine);
			//LoopNum++;
			eachLine = generateDB(eachLine, mapPredicate, lineNumberReader, out_metaFile_Loop);
			///////////////////////////////////////////////////////////////
		eachLine=lineNumberReader.readLine();
		
	}
	lineNumberReader.close();
            
    }

public static String genAssertForLoops(String eachLine, Map<String,String> mapPredicate, LineNumberReader originalFile, PrintWriter out_metaFile_V1) throws FileNotFoundException, IOException{
	for(String eachPredicate : mapPredicate.keySet()){
			if((eachLine.contains(" while(")||eachLine.contains(" while (")||eachLine.contains(" while(") ||eachLine.contains(" for(")||eachLine.contains(" for (")||eachLine.contains("  for ("))&& !eachLine.contains(" while(0)") && !eachLine.contains(" for(;0;)") && !eachLine.contains(" while(1)") && !eachLine.contains(" for(;1;)")){
				String eachPredicate1=eachPredicate.substring(1, eachPredicate.length()-1);
				//System.out.println("*********************eachPredicate "+eachPredicate1);
					if(eachPredicate1.length()!=1 && eachLine.replaceAll("\\s+","").contains(eachPredicate1)){
						String assertStmts = mapPredicate.get(eachPredicate);
						eachLine=eachLine.replace(eachLine, eachLine + assertStmts);
						if(!(eachLine.contains("||")) && !(eachLine.contains("&&"))){
							String assertStmts1 = "__CPROVER_assert("+eachPredicate1+" ,\"ASSERTION VIOLATION\");";
							String assertStmts2 = "__CPROVER_assert(! ("+eachPredicate1+") ,\"ASSERTION VIOLATION\");";
							eachLine=eachLine.replace(eachLine,eachLine + "\n" + assertStmts1 +"\n" +assertStmts2);
						}
						while(true){
							out_metaFile_V1.println(eachLine);
							out_metaFile_V1.flush();
							eachLine = originalFile.readLine();
							if(eachLine.contains("{")){
								eachLine = genAssertForLoops(eachLine, mapPredicate, originalFile, out_metaFile_V1);
							}
							if(eachLine.contains("}")){
									break;
							}
						}
						System.out.println("eachLine"+eachLine);
						System.out.println("assertStmts"+assertStmts);
						
						if(eachLine.contains("__CPROVER_assert(")){
							if(assertStmts!=null){
							eachLine=eachLine.replace(eachLine,"\n" +eachLine  +"\n" +assertStmts);}
							if(!(eachLine.contains("||")) && !(eachLine.contains("&&"))){
								String assertStmts1 = "__CPROVER_assert("+eachPredicate1+" ,\"ASSERTION VIOLATION\");";
								String assertStmts2 = "__CPROVER_assert(! ("+eachPredicate1+") ,\"ASSERTION VIOLATION\");";
								eachLine=eachLine.replace( eachLine,"\n" + eachLine+ "\n"+ assertStmts1 +"\n" +assertStmts2  );
							}
						}else{
						if(assertStmts!=null){
						eachLine=eachLine.replace(eachLine,"\n" + assertStmts +"\n" +eachLine);}
						if(!(eachLine.contains("||")) && !(eachLine.contains("&&"))){
							String assertStmts1 = "__CPROVER_assert("+eachPredicate1+" ,\"ASSERTION VIOLATION\");";
							String assertStmts2 = "__CPROVER_assert(! ("+eachPredicate1+") ,\"ASSERTION VIOLATION\");";
							eachLine=eachLine.replace( eachLine,"\n" + assertStmts1 +"\n" +assertStmts2 + "\n}" );
						}}
						
						break;
					}
			} else if((eachLine.contains("if(") || eachLine.contains("if (") || eachLine.contains(" if(") || eachLine.contains(" if (")||eachLine.contains("    if (") )&& !eachLine.contains("if(0)")  && !eachLine.contains("if(1)")){
				String eachPredicate1=eachPredicate.substring(1, eachPredicate.length()-1);
				if(eachLine.replaceAll("\\s+","").contains(eachPredicate1)){
					if(!(eachLine.contains("||")) && !(eachLine.contains("&&"))){
						String assertStmts1 = "__CPROVER_assert("+eachPredicate1+" ,\"ASSERTION VIOLATION\");";
						String assertStmts2 = "__CPROVER_assert(! ("+eachPredicate1+") ,\"ASSERTION VIOLATION\");";
						eachLine=eachLine.replace(eachLine,"\n" + assertStmts1 +"\n" +assertStmts2 + "\n" + eachLine);
					}
				}
				
			}
			
		}
		return eachLine;
	}
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	public static String generateDB(String eachLine,  Map<String,String> mapPredicate, LineNumberReader lineNumberReader, PrintWriter out_metaFile_Loop) throws IOException{
		
		if((eachLine.contains(" while(")||eachLine.contains(" while (")||eachLine.contains(" while(") ||eachLine.contains(" for(")||eachLine.contains(" for (")||eachLine.contains("  for ("))&& !eachLine.contains(" while(0)") && !eachLine.contains(" for(;0;)") && !eachLine.contains(" while(1)") && !eachLine.contains(" for(;1;)")){
				for(String eachPredicate : mapPredicate.keySet()){
				
					//System.out.println("Reading");
				String eachPredicate1=eachPredicate.substring(1, eachPredicate.length()-1);
				//System.out.println("*********************eachPredicate "+eachPredicate1);
					if(eachPredicate1.length()!=1 && eachLine.replaceAll("\\s+","").contains(eachPredicate1)){
						
						int enteringLNum = lineNumberReader.getLineNumber();
						//System.out.println("Line number of "+eachLine+" at line "+lineNumberReader.getLineNumber());
						
						String assertStmts = mapPredicate.get(eachPredicate);
						String[] lines = assertStmts.split("\r\n|\r|\n");
						int totalLines = lines.length-1;
						if(lines.length ==1){
							totalLines=2;
						}
						//System.out.println("Total Lines "+lines.length);
						while(true){
							eachLine = lineNumberReader.readLine();
							if(eachLine.contains("}")){
								//LoopNum++;
								break;
							}else if(eachLine.contains("{")){
								eachLine = generateDB(eachLine,  mapPredicate, lineNumberReader, out_metaFile_Loop);
							}
						}
						int closingLNum = lineNumberReader.getLineNumber()-1;
						
						for(int itr=1; itr<=totalLines; itr++){
							String linedata = "L"+LoopNum+";"+enteringLNum+";"+(enteringLNum+itr)+";"+((closingLNum-totalLines)+itr);
							out_metaFile_Loop.println(linedata);
							out_metaFile_Loop.flush();
							//if(itr==totalLines){LoopNum++;}
						}
						++LoopNum;
						break;
						
					}
					
				
			}
		}
		return eachLine;
	}
}
